#Install VM Pre requisites
---
- name: Enable IPVS module
  shell: 
    echo "modprobe ip_vs" >> /etc/rc.local
    modprobe ip_vs
  args:
    executable: /bin/bash
- name: Setup primary node
  hosts: ds1
  shell: 
    docker run -d --name keepalived --restart=always --cap-add=NET_ADMIN --net=host -e KEEPALIVED_UNICAST_PEERS="#PYTHON2BASH:['192.168.4.1', '192.168.4.2','192.168.4.3']" -e KEEPALIVED_VIRTUAL_IPS=192.168.4.4 -e KEEPALIVED_PRIORITY=200 osixia/keepalived:1.3.5 
  args:
     executable: /bin/bash
- name: Setup secondary nodes
  hosts: [ds2,ds3]
  shell: 
    docker run -d --name keepalived --restart=always --cap-add=NET_ADMIN --net=host -e KEEPALIVED_UNICAST_PEERS="#PYTHON2BASH:['192.168.4.1', '192.168.4.2','192.168.4.3']" -e KEEPALIVED_VIRTUAL_IPS=192.168.4.4 -e KEEPALIVED_PRIORITY=100 osixia/keepalived:1.3.5 
  args:
    executable: /bin/bash